# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargafiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='archivos',
            new_name='File',
        ),
    ]
